name: TeamCity deployment

on: push

jobs:
  # Собирается бекенд и деплоится на стейдж/review app
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Собирается бекенд и деплоится на стейдж/review app
  frontend:
    uses: ./.github/workflows/frontend-stage.yml